FROM openjdk:11

ENV FLINK_TGZ_URL=https://dlcdn.apache.org/flink/flink-1.20.2/flink-1.20.2-bin-scala_2.12.tgz
ENV FLINK_HOME=/opt/flink

WORKDIR /opt

RUN useradd flink && \
  wget -O flink.tgz "$FLINK_TGZ_URL" && \
  tar -xf flink.tgz && \
  rm flink.tgz

WORKDIR ${FLINK_HOME}

# Download connector library jars
RUN wget -P lib/plugin https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.3.0/mysql-connector-j-9.3.0.jar
RUN wget -P lib/plugin https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-sqlserver-cdc/3.4.0/flink-sql-connector-sqlserver-cdc-3.4.0.jar