<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.suntectec</groupId>
    <artifactId>datalake-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging> <!-- 定义聚合项目/父模块(不参与产生 JAR 包) -->
    <modules>
        <module>docker</module>
        <module>flink</module>
        <module>native</module>
        <module>seatunnel</module>
        <module>realtime-parent</module>
    </modules>

</project>