env {
  parallelism = 1
  job.name = "Kafka Debezium Format to SqlServer"
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  Kafka {
    plugin_output = "kafka_source"
    bootstrap.servers = "192.168.138.15:9092"
    topic = "CompatibleDebezium.INV.orders"
    start_mode = earliest
    debezium_record_include_schema = false
    format = debezium_json
    schema = {
      fields {
           after = MAP
           op = STRING
           before = MAP
           source = MAP
           ts_ms = STRING
           transaction = STRING
      }
    }
  }
}

transform {
  JsonPath {
    plugin_input = "kafka_source"
    plugin_output = "transform_json"
    columns = [
     {
        "src_field" = "after"
        "path" = "$.after"
        "dest_field" = "_after"
        "dest_type" = "string"
     },
     {
        "src_field" = "op"
        "path" = "$.op"
        "dest_field" = "_op"
        "dest_type" = "string"
     },
     {
        "src_field" = "op"
        "path" = "$.op"
        "dest_field" = "_delete"
        "dest_type" = "string"
     }
    ]
  }
}

sink {
  console{
    plugin_input = "transform_json"
  }
}