env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://192.168.138.15:3306/inventory"
    username = "root"
    password = "123456"
    table-names = ["inventory.orders"]

    startup.mode = "initial"
;     plugin_output = "mysql_source"
  }
}

transform {
  DefineSinkType {
;     plugin_input = "mysql_source"
    columns = [
        {
            column = "order_number"
            type = "bigint"
        }
    ]
;     plugin_output = "mysql_sink"
  }
}

sink {
    jdbc {
;         plugin_input = "mysql_sink"
        url = "jdbc:mysql://192.168.138.15:3306/inventory?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "123456"

        generate_sink_sql = true
        # You need to configure both database and table
        database = inventory
        table = orders_sink
        primary_keys = ["order_number"]
        field_ide = UPPERCASE
        schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
        data_save_mode="APPEND_DATA"
    }
}