env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://192.168.138.15:3306/inventory"
    username = "root"
    password = "123456"
    table-names = ["inventory.orders", "inventory.products"]

    startup.mode = "initial"
  }
}

sink {
  Console {
  }
}