env {
  parallelism = 1
  job.mode = "STREAMING"
}

source {
  Paimon {
    warehouse = "s3a://warehouse/paimon/"
    database = "inventory"
    table = "orders"
    paimon.hadoop.conf = {
        fs.s3a.access-key=MINIOROOT
        fs.s3a.secret-key=MINIOROOT
        fs.s3a.endpoint="http://192.168.138.15:19000"
        fs.s3a.path.style.access=true
        fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    }
  }
}

sink {
  Paimon {
    warehouse = "s3a://warehouse/paimon/"
    database = "inventory"
    table = "orders_sink"
    paimon.hadoop.conf = {
        fs.s3a.access-key=MINIOROOT
        fs.s3a.secret-key=MINIOROOT
        fs.s3a.endpoint="http://192.168.138.15:19000"
        fs.s3a.path.style.access=true
        fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    }
    paimon.table.primary-keys = "id"
  }
}