env {
    parallelism = 1
    job.mode = "STREAMING"
    checkpoint.interval = 5000
    read_limit.bytes_per_second = 7000000
    read_limit.rows_per_second = 400
}

source {
  SqlServer-CDC {
    base-url = "jdbc:sqlserver://192.168.138.15:1433;databaseName=inventory"
    # startup.mode="initial"
    startup.mode="latest"

    exactly_once = true
    username = "SA"
    password = "Abcd1234"
    database-names = ["inventory"]
    table-names = ["inventory.INV.orders"]
    table-names-config = [
      {
        table = "inventory.INV.orders"
        primaryKeys = ["id"]
      }
    ]
    plugin_output = "source"
  }
}

transform {
  Metadata {
    plugin_input = "source"
    metadata_fields {
        Database = database
        Table = table
        RowKind = rowKind
        EventTime = ts_ms
        Delay = delay
        Partition = partition
    }
    plugin_output = "trans_result"
  }

  Sql {
    plugin_input = "trans_result"
    plugin_output = "custom_name"
    # the query table name must same as field 'plugin_input'
    query = "select id, CURRENT_TIMESTAMP, ts_ms, FROM_UNIXTIME(CAST(1752718731 AS BIGINT), 'yyyy-MM-dd HH:mm:ss','UTC+8') as EventTime1, CAST(ts_ms as TIMESTAMP) as EventTime2, FORMATDATETIME(CAST(ts_ms as TIMESTAMP), 'yyyy-MM-dd HH:mm:ss') as EventTime3, DATEADD(CAST(ts_ms as TIMESTAMP), 8, 'HOUR') as EventTime4, FORMATDATETIME(DATEADD(CAST(ts_ms as TIMESTAMP), 8, 'HOUR'), 'yyyy-MM-dd HH:mm:ss') as EventTime5 from trans_result"
  }
}

sink {
  Console {
  plugin_input = "custom_name"
  }
}
