env {
    parallelism = 1
    job.mode = "STREAMING"
    checkpoint.interval = 10000
}

source {
  SqlServer-CDC {
    plugin_output = "source_table"

    base-url = "jdbc:sqlserver://192.168.138.15:14330;databaseName=inventory"
    startup.mode="initial"
    # startup.mode="latest"

    exactly_once = true
    username = "SA"
    # password = "Abcd1234"
    password = "YourStrong!Passw0rd"
    database-names = ["inventory"]
    table-names = ["inventory.INV.orders"]
    table-names-config = [
      {
        table = "inventory.INV.orders"
        primaryKeys = ["id"]
      }
    ]

  }
}

transform {
  Metadata {
    plugin_input = "source_table"
    metadata_fields {
        RowKind = rowKind
        EventTime = ts_ms
        Delay = delay
    }
    plugin_output = "trans_result_1"
  }

  RowKindExtractor {
    plugin_input = "trans_result_1"
    custom_field_name = "_row_kind"
    transform_type = FULL
    plugin_output = "trans_result_2"
  }
}

sink {
  Jdbc {
    plugin_input = "trans_result_2"
    driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
    url = "jdbc:sqlserver://192.168.138.15:14330;databaseName=TestDB"
    user = testdb_user
    password = "4rpr0*y#2024"
    database = "TestDB"
    table = "dbo.sink_orders_6"
    generate_sink_sql = true
  }
}
