env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  SqlServer-CDC {
    plugin_output = "table1"

    base-url = "jdbc:sqlserver://192.168.138.15:1433;databaseName=inventory"
    # startup.mode="initial"
    startup.mode="latest"

    exactly_once = true
    username = "SA"
    password = "Abcd1234"
    database-names = ["inventory"]
    table-names = ["inventory.INV.orders"]
    table-names-config = [
      {
        table = "inventory.INV.orders"
        primaryKeys = ["id"]
      }
    ]

  }
}

transform {
  Sql {
    plugin_input = "table1"
    plugin_output = "table2"
    query = "select id, created_at, FORMATDATETIME(created_at, 'yyyy-MM-dd HH:mm:ss') as format_created_at, PARSEDATETIME('2021-04-08 13:34:45','yyyy-MM-dd HH:mm:ss') as pdatetime,  FROM_UNIXTIME(1752508800000, 'yyyy-MM-dd HH:mm:ss','UTC+6') as format_unixtime from table1 where id>0"
  }
}

sink {
  Console {
    plugin_input = "table2"
  }
}