env {
    parallelism = 1
    job.mode = "STREAMING"
    checkpoint.interval = 10000
}

source {
  SqlServer-CDC {
    # plugin_output = "table1"

    base-url = "jdbc:sqlserver://192.168.138.15:1433;databaseName=inventory"
    # startup.mode="initial"
    startup.mode="latest"

    exactly_once = true
    username = "SA"
    password = "Abcd1234"
    database-names = ["inventory"]
    table-names = ["inventory.INV.orders"]
    table-names-config = [
      {
        table = "inventory.INV.orders"
        primaryKeys = ["id"]
      }
    ]

  }
}

transform {
  Replace {
    plugin_input = "fake"
    plugin_output = "fake1"
    replace_field = "order_id"
    pattern = "-"
    replacement = " "
    is_regex = true
    replace_first = false
  }
}

sink {
  Console {
    plugin_input = "fake1"
  }
}