env {
  parallelism = 1
  job.name = "SqlServer CDC to Debezium"
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  SqlServer-CDC {
    base-url = "jdbc:sqlserver://192.168.138.15:1433;databaseName=inventory"
    # startup.mode="initial"
    startup.mode = "latest"

    exactly_once = true
    username = "SA"
    password = "Abcd1234"
    database-names = ["inventory"]
    table-names = ["inventory.INV.orders"]
    table-names-config = [
      {
        table = "inventory.INV.orders"
        primaryKeys = ["id"]
      }
    ]

    # compatible_debezium_json options
    format = compatible_debezium_json
    debezium = {
        # include schema into kafka message
        key.converter.schemas.enable = false
        value.converter.schemas.enable = false
        # topic prefix
        database.server.name =  "TestDB"
    }
    # Skip fields and rows with parse errors instead of failing. Fields are set to null in case of errors.
    debezium-json.ignore-parse-errors = true
  }
}

# because sink sqlserver doesn't offer option debezium-json.ignore-parse-errors, if "op": "d", job will job fail with NullPointerException
sink {
  Jdbc {
    driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
    url = "jdbc:sqlserver://192.168.138.15:14330;databaseName=TestDB"
    user = testdb_user
    password = "4rpr0*y#2024"
    database = "TestDB"
    table = "dbo.sqlserver_debezium_orders4"
    generate_sink_sql = true
  }
}