# Flink
flink.master=192.168.138.15

# My SQL Server
my.sqlserver.host=192.168.138.15
my.sqlserver.port=14330
my.sqlserver.username=SA
my.sqlserver.password=YourStrong!Passw0rd

# SQL Server
sqlserver.host=192.168.138.15
sqlserver.port=1433
sqlserver.username=SA
sqlserver.password=Abcd1234

# Paimon
warehouse=s3://warehouse/paimon/
s3.endpoint=http://192.168.138.15:9000
s3.access-key=minioadmin
s3.secret-key=minioadmin

# Kafka
kafka.brokers=192.168.138.15:9092